arena:
  db:
    filename: <projectroot>/arena.db
  logging:
    level: DEBUG
    capture: False
    logfile: <projectroot>/arena.log
    loggers:
      factory: DEBUG
      service: DEBUG
      controller: DEBUG
  url: http://localhost:8000
  workers: 4

actor:
  db:
    filename: <projectroot>/actor.db
  logging:
    level: DEBUG
    capture: False
    logfile: <projectroot>/actor.log
    loggers:
      factory: DEBUG
      service: DEBUG
      controller: DEBUG
  url: http://localhost:8001

messagebroker:
  url: nats://localhost:4222

scheduler:
  db:
    filename: <projectroot>/arena.db
  delay: 1
  logging:
    level: DEBUG
    capture: False
    logfile: <projectroot>/scheduler.log
    loggers:
      factory: DEBUG
      service: DEBUG
      controller: DEBUG
  max_concurrent: 5
  url: http://localhost:8002

uuid:
  wordlist: <projectroot>/etc/words.csv

prod:
  better_exceptions: False

dev:
  better_exceptions: True
