db:
  filename: <projectroot>/arena.db
logging:
  core:
    level: DEBUG  
    capture: False
  scheduler:
    level: DEBUG  
    capture: False
queues:
  jobs:
    filename: <projectroot>/queue.db
scheduler:
  delay: 1
  max_concurrent: 5
server:
  workers: 4
prod:
  better_exceptions: False
dev:
  better_exceptions: True