arena:
  url: http://localhost:8000
db:
  filename: <projectroot>/arena.db
logging:
  arena:
    level: DEBUG  
    capture: False
  scheduler:
    level: DEBUG  
    capture: False
uuid:
  wordlist: <projectroot>/etc/words.csv
queues:
  jobs:
    filename: <projectroot>/queue.db
scheduler:
  delay: 1
  max_concurrent: 5
  url: http://localhost:8080
server:
  workers: 4
prod:
  better_exceptions: False
dev:
  better_exceptions: True
  