arena:
  db:
    filename: <projectroot>/arena.db
  logging:
    level: DEBUG  
    capture: False
  url: http://localhost:8000
  workers: 4

actor:
  db:
    filename: <projectroot>/actor.db
  logging:
    level: DEBUG  
    capture: False
  url: http://localhost:8001

scheduler:
  db:
    filename: <projectroot>/arena.db
  delay: 1
  logging:
    level: DEBUG  
    capture: False
  max_concurrent: 5
  url: http://localhost:8080

uuid:
  wordlist: <projectroot>/etc/words.csv

prod:
  better_exceptions: False

dev:
  better_exceptions: True
  